
services:
  db:
    image: postgres:latest
    container_name: db_escolar
    environment:
      POSTGRES_DB: escola
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_escolar
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
    restart: always

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/escola?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - postgres_exporter
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus

volumes:
  db_data:
  grafana_data: